#!/usr/bin/env node
// Generates web/ui-api.js from wit/plinth/ui-api.toml (SPEC.md §8.2).
// wit/plinth/ui-api.toml is the single source of truth for control, prop,
// event and enum ids; this script is a tiny hand-rolled reader for its
// restricted shape (`[section]` headers, `key = number # comment` lines,
// `[enums.<name>]` sub-tables) so the project needs no TOML dependency.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const src = path.join(root, "wit/plinth/ui-api.toml");
const out = path.join(root, "web/ui-api.js");

const text = readFileSync(src, "utf-8");

let version = "";
const sections = {}; // name -> { key: number }
let cur = null;

function camel(name) {
  return name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

for (const rawLine of text.split(/\r?\n/)) {
  const line = rawLine.trim();
  if (!line || line.startsWith("#")) continue;
  const sectionMatch = line.match(/^\[([\w.-]+)]$/);
  if (sectionMatch) {
    cur = sectionMatch[1];
    sections[cur] ??= {};
    continue;
  }
  const kv = line.match(/^([\w-]+)\s*=\s*"?([^"#]+?)"?\s*(#.*)?$/);
  if (!kv) continue;
  const [, key, value] = kv;
  if (cur === null && key === "version") {
    version = value.trim();
    continue;
  }
  if (cur) {
    const n = Number(value.trim());
    sections[cur][key] = Number.isNaN(n) ? value.trim() : n;
  }
}

function emitMap(name, obj) {
  const entries = Object.entries(obj)
    .map(([k, v]) => `  ${JSON.stringify(camel(k))}: ${JSON.stringify(v)},`)
    .join("\n");
  return `export const ${name} = {\n${entries}\n};\n`;
}

let js = `// GENERATED by scripts/gen-web-ids.mjs from wit/plinth/ui-api.toml.
// Do not edit by hand; re-run the script after the id table changes.

export const UI_API_VERSION = ${JSON.stringify(version)};

`;

js += emitMap("ControlKind", sections.controls ?? {});
js += "\n";
js += emitMap("Prop", sections.props ?? {});
js += "\n";
js += emitMap("Event", sections.events ?? {});
js += "\n";

for (const key of Object.keys(sections)) {
  const m = key.match(/^enums\.(.+)$/);
  if (!m) continue;
  const enumName = camel(m[1]).replace(/^(.)/, (c) => c.toUpperCase());
  js += emitMap(`Enum${enumName}`, sections[key]);
  js += "\n";
}

writeFileSync(out, js, { encoding: "utf-8" });
console.log(`wrote ${out}`);
