// GENERATED by scripts/gen-web-ids.mjs from wit/plinth/ui-api.toml.
// Do not edit by hand; re-run the script after the id table changes.

export const UI_API_VERSION = "1.12";

export const ControlKind = {
  "screen": 1,
  "section": 2,
  "text": 3,
  "heading": 4,
  "button": 5,
  "textField": 6,
  "toggle": 7,
  "list": 8,
  "row": 9,
  "empty": 10,
  "group": 11,
  "checkbox": 12,
  "textArea": 13,
  "slider": 14,
  "numberField": 15,
  "picker": 16,
  "progress": 17,
  "badge": 18,
  "tabs": 20,
  "sheet": 21,
  "dialog": 22,
  "menu": 23,
  "grid": 24,
  "action": 25,
  "image": 26,
  "icon": 27,
  "datePicker": 28,
  "chart": 29,
  "box": 30,
  "span": 31,
  "pressable": 32,
  "scroll": 33,
  "canvas": 34,
};

export const Prop = {
  "title": 1,
  "subtitle": 2,
  "label": 3,
  "value": 4,
  "placeholder": 5,
  "role": 6,
  "style": 7,
  "tone": 8,
  "level": 9,
  "disabled": 10,
  "icon": 11,
  "message": 12,
  "footer": 13,
  "error": 14,
  "axis": 15,
  "size": 16,
  "align": 17,
  "min": 18,
  "max": 19,
  "step": 20,
  "options": 21,
  "items": 30,
  "confirm": 31,
  "src": 32,
  "alt": 33,
  "aspect": 34,
  "trailing": 35,
  "mode": 36,
  "chartKind": 37,
  "data": 38,
  "series": 39,
  "wrap": 40,
  "gap": 41,
  "padding": 42,
  "paddingX": 43,
  "paddingY": 44,
  "crossAlign": 45,
  "justify": 46,
  "grow": 47,
  "width": 48,
  "widthFraction": 49,
  "height": 50,
  "heightFraction": 51,
  "maxWidth": 52,
  "maxWidthFraction": 53,
  "maxHeight": 54,
  "maxHeightFraction": 55,
  "bg": 56,
  "fg": 57,
  "border": 58,
  "radius": 59,
  "textSize": 60,
  "weight": 61,
  "italic": 62,
  "mono": 63,
  "lines": 64,
  "hover": 65,
  "active": 66,
  "focus": 67,
  "compact": 68,
  "regular": 69,
  "wide": 70,
  "selected": 71,
  "position": 72,
  "top": 73,
  "left": 74,
  "right": 75,
  "bottom": 76,
  "viewWidth": 77,
  "viewHeight": 78,
  "shapes": 79,
};

export const Event = {
  "press": 1,
  "change": 2,
  "submit": 3,
  "close": 6,
  "keyDown": 7,
  "keyUp": 8,
  "pointerDown": 9,
  "pointerMove": 10,
  "pointerUp": 11,
};

export const EnumButtonRole = {
  "default": 0,
  "primary": 1,
  "destructive": 2,
};

export const EnumTextStyle = {
  "body": 0,
  "caption": 1,
  "mono": 2,
};

export const EnumAxis = {
  "auto": 0,
  "row": 1,
  "column": 2,
};

export const EnumButtonSize = {
  "default": 0,
  "large": 1,
};

export const EnumTextAlign = {
  "start": 0,
  "center": 1,
  "end": 2,
};

export const EnumTone = {
  "default": 0,
  "muted": 1,
  "danger": 2,
  "success": 3,
};

export const EnumAspect = {
  "square": 0,
  "wide": 1,
  "tall": 2,
};

export const EnumDatePickerMode = {
  "date": 0,
  "time": 1,
  "datetime": 2,
};

export const EnumChartKind = {
  "bar": 0,
  "line": 1,
  "pie": 2,
};

export const EnumCrossAlign = {
  "stretch": 0,
  "start": 1,
  "center": 2,
  "end": 3,
};

export const EnumJustify = {
  "start": 0,
  "center": 1,
  "end": 2,
  "between": 3,
};

export const EnumFraction = {
  "none": 0,
  "auto": 1,
  "full": 2,
  "half": 3,
  "third": 4,
  "twoThirds": 5,
  "quarter": 6,
  "threeQuarters": 7,
};

export const EnumColor = {
  "none": 0,
  "background": 1,
  "surface": 2,
  "surfaceAlt": 3,
  "accent": 4,
  "danger": 5,
  "success": 6,
  "text": 7,
  "textMuted": 8,
  "onAccent": 9,
  "border": 10,
  "hover": 11,
  "selected": 12,
};

export const EnumRadius = {
  "none": 0,
  "sm": 1,
  "md": 2,
  "lg": 3,
  "full": 4,
};

export const EnumTextSize = {
  "sm": 0,
  "xs": 1,
  "md": 2,
  "lg": 3,
  "xl": 4,
  "xxl": 5,
};

export const EnumWeight = {
  "regular": 0,
  "medium": 1,
  "semibold": 2,
  "bold": 3,
};

export const EnumPressableRole = {
  "button": 0,
  "link": 1,
};

export const EnumPosition = {
  "relative": 0,
  "absolute": 1,
};

