// GENERATED by scripts/gen-web-ids.mjs from wit/plinth/ui-api.toml.
// Do not edit by hand; re-run the script after the id table changes.

export const UI_API_VERSION = "1.5";

export const ControlKind = {
  "screen": 1,
  "section": 2,
  "text": 3,
  "heading": 4,
  "button": 5,
  "textField": 6,
  "toggle": 7,
  "list": 8,
  "row": 9,
  "empty": 10,
  "group": 11,
  "checkbox": 12,
  "textArea": 13,
  "slider": 14,
  "numberField": 15,
  "picker": 16,
  "progress": 17,
  "badge": 18,
  "tabs": 20,
  "sheet": 21,
  "dialog": 22,
  "menu": 23,
  "grid": 24,
  "action": 25,
  "image": 26,
  "icon": 27,
  "datePicker": 28,
  "chart": 29,
};

export const Prop = {
  "title": 1,
  "subtitle": 2,
  "label": 3,
  "value": 4,
  "placeholder": 5,
  "role": 6,
  "style": 7,
  "tone": 8,
  "level": 9,
  "disabled": 10,
  "icon": 11,
  "message": 12,
  "footer": 13,
  "error": 14,
  "axis": 15,
  "size": 16,
  "align": 17,
  "min": 18,
  "max": 19,
  "step": 20,
  "options": 21,
  "items": 30,
  "confirm": 31,
  "src": 32,
  "alt": 33,
  "aspect": 34,
  "trailing": 35,
  "mode": 36,
  "chartKind": 37,
  "data": 38,
  "series": 39,
};

export const Event = {
  "press": 1,
  "change": 2,
  "submit": 3,
  "close": 6,
};

export const EnumButtonRole = {
  "default": 0,
  "primary": 1,
  "destructive": 2,
};

export const EnumTextStyle = {
  "body": 0,
  "caption": 1,
  "mono": 2,
};

export const EnumAxis = {
  "auto": 0,
  "row": 1,
  "column": 2,
};

export const EnumButtonSize = {
  "default": 0,
  "large": 1,
};

export const EnumTextAlign = {
  "start": 0,
  "center": 1,
  "end": 2,
};

export const EnumTone = {
  "default": 0,
  "muted": 1,
  "danger": 2,
  "success": 3,
};

export const EnumAspect = {
  "square": 0,
  "wide": 1,
  "tall": 2,
};

export const EnumDatePickerMode = {
  "date": 0,
  "time": 1,
  "datetime": 2,
};

export const EnumChartKind = {
  "bar": 0,
  "line": 1,
  "pie": 2,
};

